import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import SiteHeader from "@/components/site-header";
import { ViewTransitions } from 'next-view-transitions';
import QueryProvider from "@/contexts/query-provider";
import { cn } from "@/lib/utils";
import SiteFooter from "@/components/site-footer";

declare global {
  interface Window {
    kakao: any;
  }
} 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" className="scroll-smooth scroll-pt-20">
        <body className={cn('min-h-dvh font-sans antialiased', inter.className)}>
          <QueryProvider>
            <SiteHeader />
            {children}
          </QueryProvider>
          <SiteFooter />
        </body>
      </html>
    </ViewTransitions>
  );
}
