import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import SiteHeader from "@/components/site-header";
import { ViewTransitions } from 'next-view-transitions';
import QueryProvider from "@/contexts/query-provider";
import { cn } from "@/lib/utils";

// declare global {
//   interface Window {
//     kakao: any;
//   }
// } 카카오 오류 시

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={cn('min-h-dvh font-sans antialiased', inter.className)}>
          <QueryProvider>
            <SiteHeader />
            {children}
          </QueryProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
